[package]
name = "chateau"
version = "0.2.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
regress = "0.10"
dmfr = "0.1"
dmfr-dataset-reader = {version = "0.2"}
lazy_static = "1.5.0"
